const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

class ToolSynthesizer {
  constructor(registry, tracker) {
    this.registry = registry;
    this.tracker = tracker;
    this.scriptsDir = registry.scriptsDir;
  }

  /**
   * Synthesize a standalone, robust Node.js CLI script
   */
  synthesize({
    name,
    description,
    parameters = [],
    codeBody,
    examples = [],
    patternHash = null
  }) {
    if (!name || !description || !codeBody) {
      throw new Error('Missing required fields for tool synthesis (name, description, codeBody)');
    }

    const scriptFileName = `${name}.js`;
    const targetScriptPath = path.join(this.scriptsDir, scriptFileName);

    // Build standard script content
    const scriptContent = `#!/usr/bin/env node
/**
 * Auto-synthesized CLI Tool: ${name}
 * Description: ${description}
 * Generated by: Antigravity AI Agent Self-Toolmaker
 * Generated at: ${new Date().toISOString()}
 *
 * Usage:
 *   node .agents/scripts/${name}.js [options]
${examples.map(ex => ` *   node .agents/scripts/${name}.js ${ex}`).join('\n')}
 */

const fs = require('fs');
const path = require('path');

function printHelp() {
  console.log(\`
Tool: ${name}
Description: ${description}

Parameters:
${parameters.map(p => `  --${p.name.padEnd(16)} ${p.description || ''}${p.default !== undefined ? ` (default: ${p.default})` : ''}`).join('\n')}
  --help               Show this help message
  --json               Output result as raw JSON

Usage Examples:
${examples.map(ex => `  node .agents/scripts/${name}.js ${ex}`).join('\n')}
\`);
}

function parseArgs(argv) {
  const args = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--help' || arg === '-h') {
      args.help = true;
    } else if (arg.startsWith('--')) {
      const rawKey = arg.slice(2);
      if (rawKey.includes('=')) {
        const eqIdx = rawKey.indexOf('=');
        const k = rawKey.slice(0, eqIdx);
        const v = rawKey.slice(eqIdx + 1);
        args[k] = v;
      } else if (i + 1 < argv.length && !argv[i + 1].startsWith('--')) {
        args[rawKey] = argv[++i];
      } else {
        args[rawKey] = true;
      }
    } else {
      args._.push(arg);
    }
  }
  return args;
}

// Main Execution Body
async function run() {
  const args = parseArgs(process.argv.slice(2));

  if (args.help) {
    printHelp();
    process.exit(0);
  }

  try {
${codeBody}
  } catch (error) {
    console.error(\`❌ Error executing ${name}: \${error.message}\`);
    if (process.env.DEBUG) console.error(error.stack);
    process.exit(1);
  }
}

run();
`;

    // Write file
    fs.writeFileSync(targetScriptPath, scriptContent, 'utf8');

    // Make executable
    try {
      fs.chmodSync(targetScriptPath, '755');
    } catch (e) {}

    // Self-validate syntax and safely clean up on error
    try {
      this.validateSyntax(targetScriptPath);
    } catch (valErr) {
      if (fs.existsSync(targetScriptPath)) {
        try { fs.unlinkSync(targetScriptPath); } catch (e) {}
      }
      throw valErr;
    }

    // Register in tool registry
    this.registry.registerTool({
      name,
      description,
      scriptPath: targetScriptPath,
      args: parameters,
      examples
    });

    // If linked to pattern tracker, mark as synthesized
    if (patternHash && this.tracker) {
      this.tracker.markSynthesized(patternHash, targetScriptPath);
    }

    return {
      name,
      scriptPath: targetScriptPath,
      description
    };
  }

  validateSyntax(scriptPath) {
    try {
      execSync(`node -c "${scriptPath}"`, { stdio: 'pipe' });
      return true;
    } catch (err) {
      throw new Error(`Synthesized script failed syntax validation: ${err.message}`);
    }
  }
}

module.exports = { ToolSynthesizer };
