#!/usr/bin/env node
/**
 * Auto-synthesized CLI Tool: audit-locales
 * Description: Audit and compare translation keys across locale files (e.g., zh-CN vs en-US)
 * Generated by: Antigravity AI Agent Self-Toolmaker
 *
 * Usage:
 *   node .agents/scripts/audit-locales.js [options]
 *   node .agents/scripts/audit-locales.js --base locales/zh-CN --target locales/en-US
 *   node .agents/scripts/audit-locales.js --json
 */

const fs = require('fs');
const path = require('path');

function printHelp() {
  console.log(`
Tool: audit-locales
Description: Audit and compare translation keys across locale files (e.g., zh-CN vs en-US)

Parameters:
  --base             Base locale directory (default: locales/zh-CN)
  --target           Target locale directory to compare against (default: locales/en-US)
  --help             Show this help message
  --json             Output result as raw JSON

Usage Examples:
  node .agents/scripts/audit-locales.js --base locales/zh-CN --target locales/en-US
  node .agents/scripts/audit-locales.js --json
`);
}

function parseArgs(argv) {
  const args = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--help' || arg === '-h') {
      args.help = true;
    } else if (arg.startsWith('--')) {
      const rawKey = arg.slice(2);
      if (rawKey.includes('=')) {
        const eqIdx = rawKey.indexOf('=');
        const k = rawKey.slice(0, eqIdx);
        const v = rawKey.slice(eqIdx + 1);
        args[k] = v;
      } else if (i + 1 < argv.length && !argv[i + 1].startsWith('--')) {
        args[rawKey] = argv[++i];
      } else {
        args[rawKey] = true;
      }
    } else {
      args._.push(arg);
    }
  }
  return args;
}

function getFlattenedKeys(obj, prefix = '') {
  let keys = [];
  if (!obj || typeof obj !== 'object') return keys;
  for (const [k, v] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      keys = keys.concat(getFlattenedKeys(v, fullKey));
    } else {
      keys.push(fullKey);
    }
  }
  return keys;
}

// Main Execution Body
async function run() {
  const args = parseArgs(process.argv.slice(2));

  if (args.help) {
    printHelp();
    process.exit(0);
  }

  try {
    const baseDir = path.resolve(process.cwd(), args.base || 'locales/zh-CN');
    const targetDir = path.resolve(process.cwd(), args.target || 'locales/en-US');

    if (!fs.existsSync(baseDir)) {
      throw new Error(`Base locale dir not found: ${baseDir}`);
    }
    if (!fs.existsSync(targetDir)) {
      throw new Error(`Target locale dir not found: ${targetDir}`);
    }

    const baseFiles = fs.readdirSync(baseDir).filter(f => f.endsWith('.json'));
    const report = {
      baseLocale: path.basename(baseDir),
      targetLocale: path.basename(targetDir),
      filesAudited: baseFiles.length,
      discrepancies: []
    };

    for (const file of baseFiles) {
      const basePath = path.join(baseDir, file);
      const targetPath = path.join(targetDir, file);

      if (!fs.existsSync(targetPath)) {
        report.discrepancies.push({ file, type: 'MISSING_FILE', message: `Target file ${file} missing` });
        continue;
      }

      const baseJson = JSON.parse(fs.readFileSync(basePath, 'utf8'));
      const targetJson = JSON.parse(fs.readFileSync(targetPath, 'utf8'));

      const baseKeys = getFlattenedKeys(baseJson);
      const targetKeys = getFlattenedKeys(targetJson);

      const missingInTarget = baseKeys.filter(k => !targetKeys.includes(k));
      const extraInTarget = targetKeys.filter(k => !baseKeys.includes(k));

      if (missingInTarget.length > 0 || extraInTarget.length > 0) {
        report.discrepancies.push({
          file,
          missingInTarget,
          extraInTarget
        });
      }
    }

    if (args.json) {
      console.log(JSON.stringify(report, null, 2));
    } else {
      console.log(`=== 🌐 Locale Key Audit Result (${report.baseLocale} ➔ ${report.targetLocale}) ===`);
      console.log(`Files Audited: ${report.filesAudited}`);
      if (report.discrepancies.length === 0) {
        console.log('✅ All locale keys are 100% synchronized with zero missing entries.');
      } else {
        console.log(`⚠️ Found ${report.discrepancies.length} discrepancy item(s):`);
        for (const d of report.discrepancies) {
          console.log(`  • File: ${d.file}`);
          if (d.missingInTarget) console.log(`    Missing Keys: ${d.missingInTarget.join(', ')}`);
          if (d.extraInTarget) console.log(`    Extra Keys: ${d.extraInTarget.join(', ')}`);
        }
      }
    }

  } catch (error) {
    console.error(`❌ Error executing audit-locales: ${error.message}`);
    if (process.env.DEBUG) console.error(error.stack);
    process.exit(1);
  }
}

run();
