#!/usr/bin/env node
/**
 * Auto-synthesized CLI Tool: audit-locales
 * Description: 快速审计并比对各语言包（如 zh-CN vs en-US）之间的 Key 是否对齐
 * Generated by: Antigravity AI Agent Self-Toolmaker
 * Generated at: 2026-09-14T05:01:14.952Z
 *
 * Usage:
 *   node .agents/scripts/audit-locales.js [options]
 *   node .agents/scripts/audit-locales.js --base locales/zh-CN --target locales/en-US
 *   node .agents/scripts/audit-locales.js --json
 */

const fs = require('fs');
const path = require('path');

function printHelp() {
  console.log(`
Tool: audit-locales
Description: 快速审计并比对各语言包（如 zh-CN vs en-US）之间的 Key 是否对齐

Parameters:
  --base             基准语言目录 (如 locales/zh-CN) (default: locales/zh-CN)
  --target           待对比目标语言目录 (如 locales/en-US) (default: locales/en-US)
  --help               Show this help message
  --json               Output result as raw JSON

Usage Examples:
  node .agents/scripts/audit-locales.js --base locales/zh-CN --target locales/en-US
  node .agents/scripts/audit-locales.js --json
`);
}

function parseArgs(argv) {
  const args = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--help' || arg === '-h') {
      args.help = true;
    } else if (arg.startsWith('--')) {
      const key = arg.slice(2);
      if (i + 1 < argv.length && !argv[i + 1].startsWith('--')) {
        args[key] = argv[++i];
      } else {
        args[key] = true;
      }
    } else {
      args._.push(arg);
    }
  }
  return args;
}

// Main Execution Body
async function run() {
  const args = parseArgs(process.argv.slice(2));

  if (args.help) {
    printHelp();
    process.exit(0);
  }

  try {

    const baseDir = path.resolve(process.cwd(), args.base || 'locales/zh-CN');
    const targetDir = path.resolve(process.cwd(), args.target || 'locales/en-US');

    if (!fs.existsSync(baseDir)) {
      throw new Error(`Base locale dir not found: ${baseDir}`);
    }
    if (!fs.existsSync(targetDir)) {
      throw new Error(`Target locale dir not found: ${targetDir}`);
    }

    const baseFiles = fs.readdirSync(baseDir).filter(f => f.endsWith('.json'));
    const report = {
      baseLocale: path.basename(baseDir),
      targetLocale: path.basename(targetDir),
      filesAudited: baseFiles.length,
      discrepancies: []
    };

    for (const file of baseFiles) {
      const basePath = path.join(baseDir, file);
      const targetPath = path.join(targetDir, file);

      if (!fs.existsSync(targetPath)) {
        report.discrepancies.push({ file, type: 'MISSING_FILE', message: `Target file ${file} missing` });
        continue;
      }

      const baseJson = JSON.parse(fs.readFileSync(basePath, 'utf8'));
      const targetJson = JSON.parse(fs.readFileSync(targetPath, 'utf8'));

      const baseKeys = Object.keys(baseJson);
      const targetKeys = Object.keys(targetJson);

      const missingInTarget = baseKeys.filter(k => !targetKeys.includes(k));
      const extraInTarget = targetKeys.filter(k => !baseKeys.includes(k));

      if (missingInTarget.length > 0 || extraInTarget.length > 0) {
        report.discrepancies.push({
          file,
          missingInTarget,
          extraInTarget
        });
      }
    }

    if (args.json) {
      console.log(JSON.stringify(report, null, 2));
    } else {
      console.log(`=== 🌐 多语言包审计结果 (${report.baseLocale} ➔ ${report.targetLocale}) ===`);
      console.log(`审计文件数: ${report.filesAudited}`);
      if (report.discrepancies.length === 0) {
        console.log('✅ 所有语言包 Key 100% 对齐，无缺失项！');
      } else {
        console.log(`⚠️ 发现 ${report.discrepancies.length} 处不一致:`);
        for (const d of report.discrepancies) {
          console.log(`  • 文件: ${d.file}`);
          if (d.missingInTarget) console.log(`    缺失 Key: ${d.missingInTarget.join(', ')}`);
          if (d.extraInTarget) console.log(`    多余 Key: ${d.extraInTarget.join(', ')}`);
        }
      }
    }

  } catch (error) {
    console.error(`❌ Error executing audit-locales: ${error.message}`);
    if (process.env.DEBUG) console.error(error.stack);
    process.exit(1);
  }
}

run();
